package kharonbuilder

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// kharonRoot is the Kharon source root the builder worker uses to locate the
// beacon Makefile, the loader sources, and (below) the loader sources. It is set
// once at worker startup (the baked-in source tree inside the builder image).
var kharonRoot = ""

// SetKharonRoot points the worker at the Kharon source root (where src_beacon and
// src_loader live). Called once at startup; empty falls back to "/app/kharon"
// (the builder image's layout). Tests override it with a fixture dir.
func SetKharonRoot(p string) {
	if p == "" {
		p = "/app/kharon"
	}
	kharonRoot = p
}

// generateKharonShellcodeH renders a PIC shellcode blob as a C++ header, mirroring
// Kharon/src_server/pl_utils.go's gen_shelllcode_header verbatim (the server keeps
// this pure-Go generator; the sidecar ports it so it can write Shellcode.h from
// the beacon bytes it just built).
func generateKharonShellcodeH(shellcode []byte) string {
	var sb strings.Builder

	sb.WriteString("#pragma once\n\n")
	sb.WriteString("// Autogenerated shellcode\n")
	sb.WriteString("#include <cstdint>\n\n")
	sb.WriteString("namespace Shellcode {\n\n")
	sb.WriteString(fmt.Sprintf("    constexpr size_t Size = %d;\n\n", len(shellcode)))
	sb.WriteString("__attribute__((section(\".text\")))\n")
	sb.WriteString("const uint8_t Data[] = {\n        ")

	for i, b := range shellcode {
		if i > 0 {
			if i%12 == 0 {
				sb.WriteString(",\n        ")
			} else {
				sb.WriteString(", ")
			}
		}
		sb.WriteString(fmt.Sprintf("0x%02x", b))
	}

	sb.WriteString("\n    };\n\n")
	sb.WriteString("}\n")

	return sb.String()
}

// mingwCXXIncludePaths returns the mingw-w64 C++ standard-library include paths
// that Debian's clang++ does not know by default for -target x86_64-w64-mingw32.
// GCC keeps the C++ headers under /usr/lib/gcc/<triple>/<ver>/include/c++ and the
// arch-specific bits (which <cstdint> pulls in via <bits/c++config.h>) under
// .../c++/<triple>/bits. Both levels are returned so the loader compiles. The
// GCC version component is globbed because it is baked into the builder image
// but not otherwise discoverable; an empty result simply yields a missing-header
// error from the compiler below.
func mingwCXXIncludePaths() []string {
	const triple = "x86_64-w64-mingw32"
	var paths []string
	if top, err := filepath.Glob(filepath.Join("/usr/lib/gcc", triple, "*/include/c++")); err == nil && len(top) > 0 {
		paths = append(paths, top[0])
	}
	if arch, err := filepath.Glob(filepath.Join("/usr/lib/gcc", triple, "*/include/c++", triple)); err == nil && len(arch) > 0 {
		paths = append(paths, arch[0])
	}
	return paths
}

// compileWrapper writes Shellcode.h into the loader tree and compiles the PIC
// payload into an exe/dll/svc PE using clang++ (invoked with an explicit arg
// array, no shell). It mirrors pl_agent.go's clang++ invocation exactly. If
// clang++ is not on PATH it returns a clear "toolchain absent" error before any
// compilation is attempted.
//
// The loader is always compiled as x64 (clang++ -target x86_64-w64-mingw32),
// regardless of the beacon Target — this is an upstream limitation, preserved
// here. src/loader is Kharon/src_loader; the loader sources include Shellcode.h
// from src_loader/Include.
var compileWrapper = func(req *KharonBuildRequest, shellcode []byte) ([]byte, string, error) {
	compiler := "clang++"
	if _, err := exec.LookPath(compiler); err != nil {
		return nil, "", fmt.Errorf("toolchain %q is absent (install clang): %w", compiler, err)
	}

	// Write Shellcode.h into src_loader/Include (the loader includes it from here).
	includeDir := filepath.Join(kharonRoot, "src_loader", "Include")
	if err := os.MkdirAll(includeDir, 0o755); err != nil {
		return nil, "", fmt.Errorf("mkdir include: %w", err)
	}
	hp := filepath.Join(includeDir, "Shellcode.h")
	if err := os.WriteFile(hp, []byte(generateKharonShellcodeH(shellcode)), 0o644); err != nil {
		return nil, "", fmt.Errorf("write %s: %w", hp, err)
	}

	src, outName, ok := req.loaderSource()
	if !ok {
		return nil, "", fmt.Errorf("unknown loader format: %s", req.OutputFormat)
	}
	sourcePath := filepath.Join(kharonRoot, "src_loader", "Source", "Main", src)
	if _, err := os.Stat(sourcePath); err != nil {
		return nil, "", fmt.Errorf("loader source %s not found: %w", sourcePath, err)
	}

	// Seal: prove the Shellcode.h we just generated compiles against the pinned
	// src_loader before spending time linking a PE. This is the content-vs-pinned-
	// tree seam — if the server's beacon format drifts from what the pinned loader
	// expects, the generated header won't parse here and we fail fast with a message
	// that names the drift instead of a late link/PE failure. Syntax-only (no link)
	// keeps it fast and isolates header-vs-compiler drift from a payload packaging
	// failure (the latter surfaces later as a linker error, not a header parse error).
	if err := syntaxCheckLoader(compiler, sourcePath, includeDir); err != nil {
		return nil, "", err
	}

	binDir := filepath.Join(kharonRoot, "src_loader", "Bin")
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return nil, "", fmt.Errorf("mkdir bin: %w", err)
	}
	outPath := filepath.Join(binDir, outName)

	clangArgs := []string{
		"-target", "x86_64-w64-mingw32",
		"-I", includeDir,
		"-o", outPath,
		sourcePath,
		"-Os",
		"-mwindows",
		"-nostdlib",
		"-s",
		"-lkernel32",
		"-ladvapi32",
	}

	// clang++ (Debian's) knows the mingw C headers (/usr/x86_64-w64-mingw32/include,
	// so <windows.h> resolves) but not the mingw C++ standard library, which GCC
	// keeps under /usr/lib/gcc/<triple>/<ver>/include/c++ with arch-specific bits
	// under .../c++/<triple>/bits. The loader's Shellcode.h includes <cstdint>, so
	// add both levels. The version component is globbed (baked into the builder
	// image but not otherwise discoverable); if neither path exists the loader
	// simply fails with a missing-header error below.
	for _, p := range mingwCXXIncludePaths() {
		clangArgs = append(clangArgs, "-I", p)
	}
	if req.OutputFormat == "dll" {
		clangArgs = append(clangArgs, "-shared")
	}

	cmdOut, cmdErr := exec.Command(compiler, clangArgs...).CombinedOutput()
	if cmdErr != nil {
		return nil, "", fmt.Errorf("%s failed: %v\n%s", compiler, cmdErr, string(cmdOut))
	}

	peBytes, err := os.ReadFile(outPath)
	if err != nil {
		return nil, "", fmt.Errorf("read output PE: %w", err)
	}
	return peBytes, outName, nil
}

// syntaxCheckLoader runs clang++ -fsyntax-only on the loader source against the
// same include set as the real compile, proving the generated Shellcode.h parses
// against the pinned src_loader before the (expensive) link step. It isolates
// content-vs-pinned-tree drift (server generator vs pinned compiler) from a payload
// packaging failure, so a beacon-format change fails locally and with a message that
// tells the operator which side to align. Syntax-only intentionally omits the link
// flags (-mwindows/-nostdlib/-s/-l*); they don't affect header parsing and only slow
// the check, and -fsyntax-only stops after semantic analysis so no linking happens.
func syntaxCheckLoader(compiler, sourcePath, includeDir string) error {
	args := []string{"-target", "x86_64-w64-mingw32", "-fsyntax-only", "-I", includeDir}
	for _, p := range mingwCXXIncludePaths() {
		args = append(args, "-I", p)
	}
	args = append(args, sourcePath)
	if _, err := exec.Command(compiler, args...).CombinedOutput(); err != nil {
		return fmt.Errorf(
			"generated Shellcode.h does not compile against pinned src_loader: "+
				"server beacon format or pinned loader tree is out of sync "+
				"(regenerator vs compiler drift). Align the beacon generator with the "+
				"pinned src_loader or refresh the pinned tree.\n%s", err)
	}
	return nil
}
